cache:
  paths:
    - node_modules/

pages:
  image: node:latest
  stage: build
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[build\]/
      - $CI_COMMIT_REF_NAME == "master"
  script:
    - npm install
    - mkdir -p build public
    - npm run production
    - mv build/* public/
  artifacts:
    paths:
      - public
